// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXHMpu3sWu9PRmwOs75VZCK-MnTlWMQo4',
    appId: '1:470133712629:web:f6d624a3bbdca3273a47bc',
    messagingSenderId: '470133712629',
    projectId: 'chat-app-3c284',
    authDomain: 'chat-app-3c284.firebaseapp.com',
    storageBucket: 'chat-app-3c284.appspot.com',
    measurementId: 'G-2V6G4SMZSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmyaO0JRttUohDvzJXkWq-hyVVZKot8iw',
    appId: '1:470133712629:android:0646ed0a998061743a47bc',
    messagingSenderId: '470133712629',
    projectId: 'chat-app-3c284',
    storageBucket: 'chat-app-3c284.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaELIHegcemIqTU15KXV3hdsZyiCzIyRk',
    appId: '1:470133712629:ios:56dcb0a7a20dbb7f3a47bc',
    messagingSenderId: '470133712629',
    projectId: 'chat-app-3c284',
    storageBucket: 'chat-app-3c284.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaELIHegcemIqTU15KXV3hdsZyiCzIyRk',
    appId: '1:470133712629:ios:4b0b237cac6679cc3a47bc',
    messagingSenderId: '470133712629',
    projectId: 'chat-app-3c284',
    storageBucket: 'chat-app-3c284.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
